### ISSUE TITLE
✨ Feature: Frontmatter

### ISSUE THREAD

**Issue by mikaeleythor** [OXY2DEV/markview.nvim#168]
### The nature of the feature:

- [X] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Would be pretty cool to render frontmatter. E.g. by hiding the hyphens and changing the highlight groups of the tags.
```txt
---
date: 2024-10-06
date_modified: 2024-10-06
tags: [engineering, machine-learning, HR, DATA]
---
```
could look like this
```yaml
date: 2024-10-06
date_modified: 2024-10-06
tags: [engineering, machine-learning, HR, DATA]
```
